name: gitleaks
on: [pull_request, push, workflow_dispatch]
jobs:
  scan:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run Gitleaks Scan
        uses: gitleaks/gitleaks-action@v2
        with:
          args: --config=.gitleaks.toml --no-fail
        continue-on-error: true  # Ensure the workflow continues even if secrets are found
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

