name: gitleaks
on: [pull_request, push, workflow_dispatch]
jobs:
  scan:
    name: gitleaks
    runs-on: ubuntu-22.04
    permissions:
      pull-requests: write
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run Gitleaks Scan
        uses: gitleaks/gitleaks-action@v2
        with:
          config: .gitleaks.toml  # Specify your custom Gitleaks config file if needed
          fail_on_new_secrets: false  # Avoid failing the job if new secrets are found
          report_format: json  # Report format in JSON
          report_path: gitleaks-report.json  # Path where the report will be saved
        continue-on-error: true  # Ensures the workflow continues even if secrets are found
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Gitleaks Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: gitleaks-report
          path: gitleaks-report.json


