name: gitleaks
on: [pull_request, push, workflow_dispatch]
jobs:
  scan:
    name: gitleaks
    runs-on: ubuntu-22.04 # Explicitly specify the Ubuntu version
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run Gitleaks Scan
        uses: gitleaks/gitleaks-action@v2
        with:
          args: --config=.gitleaks.toml --no-fail
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
